language: python
python:
  - 3.6
  - 3.5

# Python 3.7 currently (early 2019) needs a newer Ubuntu version than the
# default image on Travis.
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  global:
    - MPLBACKEND=agg
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

install:
  - make dev-install
  - pip install codecov

before_script:
    - sudo apt install libnetcdf-dev python3-netcdf4 cdo python3-cdo

script:
  - echo $PATH
  - which cdo
  - make test

after_success: codecov
